name: TrueYoga
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  # State Management
  provider: ^6.0.0
  cloud_firestore: ^2.5.0
  firebase_core: ^1.5.0
  shared_preferences: ^2.0.6
  url_launcher: ^6.0.9
  page_transition: ^2.0.2
  intl: ^0.17.0
  flutter_svg: ^0.22.0
  expandable: ^5.0.1
  smooth_page_indicator: ^1.0.0+2
  # Countdown Timer
  circular_countdown_timer: ^0.2.0
  timer_count_down: ^2.2.0
  # Icons
  ionicons: ^0.1.2
  # Toast messages
  flutter_styled_toast: ^2.0.0
  # Local DB
  sqflite: ^2.0.0+4
  # Audio Player
  just_audio: ^0.9.10
  # Animation
  auto_animated: ^3.0.0
  # 
  path_provider: ^2.0.3
  # Google Ads
  google_mobile_ads: ^0.13.5
  native_admob_flutter: ^1.5.0
  share: ^2.0.4
  device_info: ^2.0.2
  flutter_email_sender: ^5.0.2
  video_player: ^2.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/audio/
    - assets/homepagetiles/
    - assets/svg/
    - assets/workoutgif/

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
        - asset: fonts/Montserrat-Light.ttf
        - asset: fonts/Montserrat-Medium.ttf
        - asset: fonts/Montserrat-Bold.ttf
          weight: 600
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  
